CREATE TABLE "wallet_connect_pending_connections" (
	"pairing_topic" text PRIMARY KEY NOT NULL,
	"owner" text NOT NULL,
	"default_chain_id" integer NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wallet_connect_session_operations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wallet_connect_session_operations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"request_id" bigint NOT NULL,
	"topic" text NOT NULL,
	"method" text NOT NULL,
	"chain_id" text NOT NULL,
	"params" jsonb NOT NULL,
	"status" text NOT NULL,
	"timestamp_ms" bigint NOT NULL,
	"result" jsonb,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wallet_connect_sessions" (
	"topic" text PRIMARY KEY NOT NULL,
	"owner" text NOT NULL,
	"address" text NOT NULL,
	"default_chain_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "wallet_connect_pending_connections_expires_at_idx" ON "wallet_connect_pending_connections" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "wallet_connect_session_operations_topic_idx" ON "wallet_connect_session_operations" USING btree ("topic");--> statement-breakpoint
CREATE INDEX "wallet_connect_session_operations_topic_id_idx" ON "wallet_connect_session_operations" USING btree ("topic","id");--> statement-breakpoint
CREATE INDEX "wallet_connect_session_operations_id_idx" ON "wallet_connect_session_operations" USING btree ("id");--> statement-breakpoint
CREATE INDEX "wallet_connect_sessions_owner_idx" ON "wallet_connect_sessions" USING btree ("owner");